export const FORM_DATA = 'FORM_DATA'
export const HOME_FETCH_NAV = 'HOME_FETCH_NAV'
export const HOME_FETCH_SHOP = 'HOME_FETCH_SHOP'
export const CITY_FETCH_HOT = 'CITY_FETCH_HOT'
export const CITY_FETCH_ALL = 'CITY_FETCH_ALL'
export const CITY_FETCH_QUERY = 'CITY_FETCH_QUERY'
export const CITY_FETCH_SEARCH = 'CITY_FETCH_SEARCH'
export const SHOP_FETCH_FOOD = 'SHOP_FETCH_FOOD'

